### PR TITLE
Misc fixes encountered during setup

### PR DESCRIPTION
**Pull request by spiffxp**
See individual commits for details

### CODE REVIEW

**Comment by mikeln** [comment]
Not sure I like the kubectl version check being so rigid.  In reality, it only really matters that the version is greater than the last one that had an API change that affected these scripts (and in twissandra-container).  That means that currently you need to run version 0.15.0 +  of kubernetes.  

Kraken however is a different story.  It requires a more specific version of kubernetes.  But we should not attempt to check that here, as these demos can run on any cluster, not just our kraken cluster.

**Comment by mikeln** [comment]
The version should only check the API version needed: currently v1beta3
There is a command for that:

      $ kubectl api-versions
      Available Server Api Versions: v1beta1,v1beta2,v1beta3

**Comment by spiffxp** [comment]
I can't seem to find a way to verify both success and failure for API versions matching up without having a working server.  The client does't provide a way to list the API versions it supports.  With a working server, you can just try using the client to talk to server, eg `kubectl version`.  It will auto-negotiate the API, and error out if it can't match the server's version.  

Without a working server, if the client is given what looks like a valid API version, it will hang on trying to connect to the API server.

We could just consolidate to running `kubectl version` and assume success means both: a working server, and compatible API versions.

**Comment by mikeln** [comment]
Perhaps some of my intentions in the script are unclear.  
The `kubectl version` call was only meant to test if a cluster is accessible (which means: a) my kubeconfig is valid, and b) there is a running master). It was never there to provide any version checking...though the printout provides interesting information.  Also, at one time it "fast failed"...faster than  `kubectl get nodes` did.    Originally, I used `kubectl get nodes` to check for the availability of a cluster to use. That call is still there for: a) for debug information about the cluster, b) future additional "fail safe" checks on cluster size.

As for the addition of version checking, I think that API version checking is a good idea, and I would put that after the first call to `version` before `get nodes`, and check that the  `api-version` has `v1beta3`...but only if it gets past the "determine if cluster is available" phase. (i.e. `version`).

**Comment by mikeln** [comment]
LGTM

**Pull request merged**
